# Generated by Django 4.1.1 on 2022-09-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saves',
            name='image',
            field=models.ImageField(upload_to='main/static/'),
        ),
    ]
