# Generated by Django 4.1.1 on 2022-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_saves_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='saves',
            name='from_user',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saves',
            name='to_user',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
