# Generated by Django 4.1.1 on 2022-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_saves_from_user_saves_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saves',
            name='done_img',
            field=models.ImageField(default='', upload_to='main/static/done_img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saves',
            name='image',
            field=models.ImageField(upload_to='main/static/user_img/'),
        ),
    ]
